### ISSUE TITLE
Cannot run anything from Neo4j.Sips

### ISSUE THREAD

**Issue by neildsouza** [florinpatrascu/neo4j_sips#16]
Hi,
Am getting an issue when running Neo4j.Sips.
My config.exs file contains ...

```
config :neo4j_sips, Neo4j,
  url: "http://localhost:7474",
  pool_size: 5,
  max_overflow: 2,
  timeout: 30
```

``` elixir
iex(2)> Neo4j.Sips.config
** (MatchError) no match of right hand side value: []
    (con_cache) lib/con_cache/registry.ex:18: ConCache.Registry.get/1
    (con_cache) lib/con_cache.ex:143: ConCache.get/2
iex(2)> Neo4j.Sips.conn
** (MatchError) no match of right hand side value: []
    (con_cache) lib/con_cache/registry.ex:18: ConCache.Registry.get/1
    (con_cache) lib/con_cache.ex:143: ConCache.get/2
iex(2)>
```

Any help with this would be greatly appreciated.

Thnx.

**Comment by neildsouza** [comment]
1000 apologies ... problem solved.
Had not read the manual properly :(

**Comment by florinpatrascu** [comment]
Glad you figured it out :)

**Comment by tyronewilson** [comment]
@neildsouza any chance you could tell us what the issue was? I have followed the manual but I am lost. It looks simple but I can't understand what I am doing wrong.

**Comment by florinpatrascu** [comment]
@tyronewilson - I believe you didn't start the app?! You must use Neo4j.Sips.start_link/1 first, before getting any Connections. And if that's the case, then the cache was not started. Here, my test Neo4j instance runs on 7373:

```
iex(1)> Neo4j.Sips.start_link(url: "http://localhost:7373")
{:ok, #PID<0.195.0>}
iex(2)> Neo4j.Sips.conn
%Neo4j.Sips.Connection{commit_url: "", options: nil,
 server: %Neo4j.Sips.Server{data: %{batch: "http://localhost:7373/db/data/batch",
    constraints: "http://localhost:7373/db/data/schema/constraint",
    cypher: "http://localhost:7373/db/data/cypher", extensions: %{},
    extensions_info: "http://localhost:7373/db/data/ext",....
```

HTH
